name: contracts_of_data_sources
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1 # Your SDK version might vary, keep what you have if it's different

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  internet_connection_checker_plus: ^2.7.2
  shared_preferences: ^2.0.0
  http: ^1.2.0

  # ADDED for BLoC implementation
  flutter_bloc: ^8.1.3 # Official BLoC package for Flutter
  equatable: ^2.0.5   # For comparing objects in events and states easily

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.0

  # ADDED for BLoC testing
  bloc_test: ^9.1.5 # For testing BLoCs

flutter:
  uses-material-design: true