name: contracts_of_data_sources
description: "A Number Trivia app built with Flutter using Clean Architecture and TDD"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # More flexible version constraint

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  uuid: ^4.2.2
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  provider: ^6.1.1
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.9.2
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  dartz: ^0.10.1
  intl: ^0.18.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  mocktail: ^1.0.0

  # ADDED for BLoC testing
  bloc_test: ^9.1.5  # Version compatible with flutter_bloc 8.x

flutter:
  uses-material-design: true